train:
  _target_: src.datasets.IDMTDataset
  part: "train"
  effect_type: "Chorus"
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.IDMTDataset
  part: "val"
  effect_type: "Chorus"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.IDMTDataset
  part: "test"
  effect_type: "Chorus"
  instance_transforms: ${transforms.instance_transforms.train}
