device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.Plug
    name: "Plug"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.Plug
    name: "Plug"
