device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.MeanSquaredErrorMetric
    name: "MSE metric"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MeanSquaredErrorMetric
    name: "MSE metric"
