train:
  input_spec:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
  output_spec:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
inference:
  input_spec:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
  output_spec:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
