train:
  input_audio:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
  output_audio:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
inference:
  input_audio:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
  output_audio:
    _target_: src.transforms.Normalize1D
    mean: 0
    std: 1
