defaults:
  - model: audiomae
  - writer: wandb
  - metrics: audiomae
  - datasets: train
  - dataloader: audiomae
  - transforms: audiomae
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 2e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 82500
loss_function:
  _target_: src.loss.MSELoss
trainer:
  log_step: 50
  n_epochs: 100
  device_tensors: ["input_spec", "output_spec"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 8 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
