defaults:
  - model: baseline # specify the model
  - metrics: example # specify the metrics
  - datasets: example_eval # specify the desired dataset, as we do not want to run inference on training data
  - dataloader: example # specify the dataloader
  - transforms: example # specify the transforms
  - _self_
inferencer:
  device_tensors: ["input_audio", "output_audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # specify path to the pretrained model
