defaults:
  - model: pretrain
  - writer: wandb
  - metrics: baseline
  - datasets: pretrain
  - dataloader: baseline
  - transforms: pretrain
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 82500
loss_function:
  _target_: src.loss.MRSTFTLoss
trainer:
  log_step: 50
  n_epochs: 30
  device_tensors: ["input_audio", "output_audio"]
  resume_from: null
  device: auto
  override: True
  monitor: "off"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
