train:
  input_audio:
    _target_: src.transforms.FrameOutput
  output_audio:
    _target_: src.transforms.FrameOutput
inference:
  input_audio:
    _target_: src.transforms.FrameOutput
  output_audio:
    _target_: src.transforms.FrameOutput